version: "3.4"
services:
  mqtt:
    image: eclipse-mosquitto
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mosquitto/config.conf:/mosquitto/config/mosquitto.conf
  ruuvigw-poll-mqtt:
    image: ruuvigw-poll-mqtt
    build:
      context: .
    links:
      - mqtt
    env_file: 
      - docker.env